from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select


driver = webdriver.Chrome()
driver.get("https://www.tutorialspoint.com/selenium/practice/selenium_automation_practice.php")
driver.maximize_window()
time.sleep(3)
search = driver.find_element(By.ID, "name")
search.send_keys("Anusathya G")
time.sleep(1)
search = driver.find_element(By.CSS_SELECTOR, "#email")
search.send_keys("anusathyagurusamy@gmail.com")
time.sleep(1)
search = driver.find_element(By.XPATH,"(//input[@type='radio'])[2]")
search.click()
time.sleep(1)
search = driver.find_element(By.CSS_SELECTOR, "#mobile")
search.send_keys("8148148148")
time.sleep(1)
search = driver.find_element(By.NAME, "dob")
search.send_keys("25/06/2026")
time.sleep(1)
search = driver.find_element(By.ID, "subjects")
search.send_keys("Python")
time.sleep(1)
search = driver.find_element(By.XPATH,"//input[@type='checkbox']")
search.click()
time.sleep(1)
picture = driver.find_element(By.ID, "picture")
picture.send_keys("C:/Users/admin/Desktop/PythonTesting/Locators_Py.docx")
time.sleep(2)
address = driver.find_element(By.XPATH, '/html/body/main/div/div/div[2]/form/div[9]/div/textarea')
address.send_keys("Madurai")
time.sleep(2)
country = driver.find_element(By.ID, "state")
dd = Select(country)
dd.select_by_index(1)
time.sleep(3)
city = driver.find_element(By.NAME, "city")
dd = Select(city)
dd.select_by_index(1)
time.sleep(3)
submit = driver.find_element(By.CSS_SELECTOR, "input[value='Login']")
submit.click()
